In [3]:
import torch

## TorchのTensorになれる
https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py
を見ても問題ないです。

In [4]:
x = torch.empty(5, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [5]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2716, 0.2662, 0.3139],
        [0.4459, 0.5422, 0.7127],
        [0.2916, 0.0959, 0.0488],
        [0.5378, 0.0722, 0.3648],
        [0.9261, 0.0121, 0.4939]])


In [6]:
y = torch.zeros(5, 3, dtype=torch.double)
print(y)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)


In [7]:
y + x

tensor([[0.2716, 0.2662, 0.3139],
        [0.4459, 0.5422, 0.7127],
        [0.2916, 0.0959, 0.0488],
        [0.5378, 0.0722, 0.3648],
        [0.9261, 0.0121, 0.4939]], dtype=torch.float64)

In [8]:
x = torch.tensor([5.5, 3])
print(x)
x = x.new_ones(5, 3, dtype=torch.double)      # 5×3の1を作成,引数の指定がない場合,dtype,deviceを引き継ぐ
print(x)
x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                        

tensor([5.5000, 3.0000])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.1027,  1.5659,  1.0646],
        [-0.0143, -0.3909,  0.3023],
        [-0.2554,  1.1222,  1.7798],
        [ 0.7319, -0.6454, -0.5508],
        [ 1.2516,  0.7592,  1.3083]])


tensor([[ 1.1027,  1.5659,  1.0646],
        [-0.0143, -0.3909,  0.3023],
        [-0.2554,  1.1222,  1.7798],
        [ 0.7319, -0.6454, -0.5508],
        [ 1.2516,  0.7592,  1.3083]], dtype=torch.float64)


###  足し算/掛け算

In [10]:
y = torch.rand(5, 3)
print(x + y)

result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)
x * 7

tensor([[ 1.8216,  2.2471,  1.4945],
        [ 0.7065,  0.5375,  0.9956],
        [ 0.1100,  1.1816,  2.5897],
        [ 0.7481, -0.2171, -0.4697],
        [ 2.1221,  1.6942,  2.0853]])
tensor([[ 1.8216,  2.2471,  1.4945],
        [ 0.7065,  0.5375,  0.9956],
        [ 0.1100,  1.1816,  2.5897],
        [ 0.7481, -0.2171, -0.4697],
        [ 2.1221,  1.6942,  2.0853]])


tensor([[ 7.7186, 10.9614,  7.4522],
        [-0.0999, -2.7365,  2.1159],
        [-1.7880,  7.8556, 12.4584],
        [ 5.1230, -4.5175, -3.8558],
        [ 8.7614,  5.3145,  9.1584]])

### 足し算(inplace)

In [12]:
y.add_(x)
print(y)

tensor([[ 2.9243,  3.8131,  2.5591],
        [ 0.6922,  0.1466,  1.2978],
        [-0.1455,  2.3038,  4.3694],
        [ 1.4800, -0.8625, -1.0205],
        [ 3.3737,  2.4534,  3.3937]])


In [16]:
# 型の変更
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [15]:
# Pytorch TensorからPythonの数値型の要素を取得
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.1116])
0.11159460991621017


In [17]:
# Numpyに変更
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


## 自動微分

In [59]:
X1 = torch.tensor(3. , requires_grad=True)
X2 = torch.tensor(2., requires_grad=True)

Y1 = 3*X1 + 2*X2
Y2 = 4*X1 + X2

In [62]:
print(torch.autograd.grad(Y1, [X1, X2], retain_graph=True))
print(torch.autograd.grad(Y2, [X1, X2], retain_graph=True))

(tensor(3.), tensor(2.))
(tensor(4.), tensor(1.))


## ざっくりした機械学習の動作

In [21]:
# 定数の準備
dtype = torch.float
device = torch.device("cpu")
N, D_in, H, D_out = 64, 1000, 100, 10

# データの作成
x = torch.randn(N, D_in, device=device, dtype=dtype)
y = torch.randn(N, D_out, device=device, dtype=dtype)

# パラメータの初期化
# requires_grad = Trueで勾配を覚える設定を追加
w1 = torch.randn(D_in, H, device=device, dtype=dtype, requires_grad=True)
w2 = torch.randn(H, D_out, device=device, dtype=dtype, requires_grad=True)

In [23]:
# 損失を最小になるように変更する

In [22]:
learning_rate = 1e-6
for t in range(500):
    # 1. 行列w1ををかける
    # 2. 活性化関数ReLUを合成
    # 3. もう一度行列をかける
    y_pred = x.mm(w1).clamp(min=0).mm(w2)

    # 二乗の誤差を評価
    loss = (y_pred - y).pow(2).sum()
    if t % 100 == 99:
        # 進捗を表示
        print(t, loss.item())

    # lossに対する偏微分を実行
    # requires_grad = Trueにしたものに偏微分が設定される
    loss.backward()

    # パラメータの更新
    # no_gradにするのはこの操作に対する勾配が必要ないので
    # 実際に実装する時はSGDで行う事が多い
    with torch.no_grad():
        w1 -= learning_rate * w1.grad
        w2 -= learning_rate * w2.grad

        # Manually zero the gradients after updating weights
        w1.grad.zero_()
        w2.grad.zero_()

99 481.8187255859375
199 1.5556501150131226
299 0.008751582354307175
399 0.00021722674136981368
499 4.02675723307766e-05


In [20]:
x.grad

# NNのテンプレ(一旦こんな感じというのさえわかっていただければ良いです)

## NNの作成
- Dataset/DataLoaderでデータを作成
- nn.Moduleでネットワーク作成
- 最適化の設定
- 学習
- 評価


In [25]:
# パッケージimport
from torchvision import datasets, transforms
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

## データ読み込み

In [35]:
batch_size = 32
train_loader = torch.utils.data.DataLoader(
    datasets.MNIST('../data', train=True, download=True,
                   transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Normalize((0.1307,), (0.3081,))
                   ])),
    batch_size=batch_size, shuffle=True)
test_loader = torch.utils.data.DataLoader(
    datasets.MNIST('../data', train=False, download=True,
                   transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Normalize((0.1307,), (0.3081,))
                   ])),
    batch_size=batch_size, shuffle=True)

## Networkの作成

In [30]:
class Net(nn.Module):
    def __init__(self, input_size, output_size):
        super(Net, self).__init__()
        self.input_size = input_size
        self.output_size = output_size
        self.linear = nn.Linear(input_size, output_size)
    
    def forward(self, x):
        x = x.view(-1, self.input_size) # reshape
        return self.linear(x)

## 最適化の設定

In [32]:
input_size = 28 * 28
output_size = 10
model = Net(input_size, output_size)
criterion = nn.CrossEntropyLoss() # 損失の定義
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate) # (確率的)勾配降下法

## 学習

In [33]:
model.train() # 学習用のモード
for epoch, (data, target) in enumerate(train_loader): # 入力と正解
     optimizer.zero_grad() #Weightの初期化
     output = model(data) # 仮説で値代入
     loss = criterion(output, target) # 損失
     loss.backward() # 微分の計算
     optimizer.step() # パラメータの更新
     if epoch % 600 == 0:
         print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
             epoch, epoch * len(data), len(train_loader.dataset),
             100. * epoch / len(train_loader), loss.item()))

Train Epoch: 0 [0/60000 (0%)]	Loss: 2.360560
Train Epoch: 600 [19200/60000 (32%)]	Loss: 2.227802
Train Epoch: 1200 [38400/60000 (64%)]	Loss: 2.398287
Train Epoch: 1800 [57600/60000 (96%)]	Loss: 2.225083


## 評価

In [36]:
model.eval()
test_loss = 0
correct = 0
with torch.no_grad():
    for data, target in test_loader:
        output = model(data)
        test_loss += F.nll_loss(output, target, reduction='sum').item() # sum up batch loss
        pred = output.argmax(dim=1, keepdim=True) # get the index of the max log-probability
        correct += pred.eq(target.view_as(pred)).sum().item()

test_loss /= len(test_loader.dataset)

print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(
    test_loss, correct, len(test_loader.dataset),
    100. * correct / len(test_loader.dataset)))


Test set: Average loss: 0.0454, Accuracy: 1054/10000 (11%)



今回はデータをすべて一度しか使っておらず、学習は収束していない。 そのため、何回か学習を繰り返すことで評価データの精度も向上する。

## 演習1

In [77]:
print(torch.cuda.is_available())

False


## 演習2

In [68]:
print(torch.autograd.grad(torch.exp(X1), X1))
print(torch.autograd.grad(torch.cos(X1), X1))
print(torch.autograd.grad(torch.sin(X1), X1))
print(torch.autograd.grad(X1 ** 2, X1))
print(torch.autograd.grad(torch.exp(3 *X1)/(torch.exp(3*X1) + torch.exp(2*X1)), X1))

(tensor(20.0855),)
(tensor(-0.1411),)
(tensor(-0.9900),)
(tensor(6.),)
(tensor(0.0452),)


## 演習3

In [75]:
y = torch.exp(3 *X1)/(torch.exp(3*X1) + torch.exp(2*X1))
z1 = torch.exp(y)
z2 = torch.cos(y)
z3 = torch.sin(y)
z4 = y * y
z5 = torch.exp(3 *y)/(torch.exp(3*y) + torch.exp(2*y))

In [76]:
print(torch.autograd.grad(z1, X1,retain_graph=True))
print(torch.autograd.grad(z2, X1,retain_graph=True))
print(torch.autograd.grad(z3, X1,retain_graph=True))
print(torch.autograd.grad(z4, X1,retain_graph=True))
print(torch.autograd.grad(z5, X1,retain_graph=True))

(tensor(0.1171),)
(tensor(-0.0368),)
(tensor(0.0262),)
(tensor(0.0861),)
(tensor(0.0091),)
