## 演習1

以下を実装
- AND
- OR
- NAND
- XOR

In [2]:
def AND(x, y):
    w_1 = 0.5
    w_2 = 0.5
    theta = 0.7
    return 1 if  w_1 * x + w_2 * y >= theta else 0

In [3]:
print(AND(1, 0), AND(0, 1), AND(0, 0), AND(1, 1))

0 0 0 1


In [4]:
def OR(x, y):
    w_1 = 0.5
    w_2 = 0.5
    theta = 0.3
    return 1 if  w_1 * x + w_2 * y >= theta else 0

In [5]:
print(OR(1, 0), OR(0, 1), OR(0, 0), OR(1, 1))

1 1 0 1


In [6]:
def NAND(x, y):
    w_1 = - 0.5
    w_2 = - 0.5
    theta = - 0.7
    return 1 if  w_1 * x + w_2 * y >= theta else 0

In [7]:
print(NAND(1, 0), NAND(0, 1), NAND(0, 0), NAND(1, 1))

1 1 1 0


In [8]:
def XOR(x, y):
    return AND(NAND(x, y), OR(x, y))

In [9]:
print(XOR(1, 0), XOR(0, 1), XOR(0, 0), XOR(1, 1))

1 1 0 0


演習
- 3層のNNを実装

In [5]:
import torch
import torch.nn as nn

In [9]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.l1 = nn.Linear(3, 5)
        self.l2 = nn.Linear(5, 4)

    def forward(self, x):
        y = self.l1(x)
        y = self.l2(y)
        return y

In [10]:
net = Net()
x = torch.arange(3).float()
net(x)

tensor([-1.0873, -0.3053, -0.1162, -0.0916], grad_fn=<AddBackward0>)

## 演習
IRISをSGDで学習

In [19]:
from pathlib import Path
from collections import namedtuple

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

import torch
from torchvision import datasets, transforms
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [84]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.l1 = nn.Linear(4, 10)
        self.l2 = nn.Linear(10, 8)
        self.l3 = nn.Linear(8, 3)
    
    def forward(self ,x):
        x = F.relu(self.l1(x))
        x = F.relu(self.l2(x))
        return self.l3(x)

def train_epoch(model, data_loader, epoch):
    model.train()
    for batch_idx, (data, target) in enumerate(data_loader): # 入力と正解
         optimizer.zero_grad() # Weightの初期化
         output = model(data) # 仮説で値代入
         output.dtype
         loss = criterion(output, target) # 損失
         loss.backward() # 微分の計算
         optimizer.step() # パラメータの更新
         
    if epoch % 10 == 0:
        print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
            batch_idx, batch_idx * len(data), len(data_loader.dataset),
            100. * batch_idx / len(data_loader), loss.item()))

def valid_epoch(model, data_loader, epoch):
    model.valid()
    with torch.no_grad():
        for batch_idx, (data, target) in enumerate(data_loader): # 入力と正解
             optimizer.zero_grad() # Weightの初期化
             output = model(data) # 仮説で値代入
             output.dtype
             loss = criterion(output, target) # 損失
            
        if epoch % 10 == 0:
             print('Test Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                 batch_idx, batch_idx * len(data), len(data_loader.dataset),
                 100. * batch_idx / len(data_loader), loss.item()))


In [82]:
iris = load_iris()
X_train, X_valid, y_train, y_valid = train_test_split(iris.data, iris.target, test_size=0.2)

X_train = torch.tensor(X_train).float()
y_train = torch.tensor(y_train)
X_valid = torch.tensor(X_valid).float()
y_valid = torch.tensor(y_valid)

train_dataset = torch.utils.data.TensorDataset(X_train, y_train)
valid_dataset = torch.utils.data.TensorDataset(X_valid, y_valid)

model = Net()

batch_size  = 3 # ミニバッチのデータの数
max_epoch = 100 #
train_loader = torch.utils.data.DataLoader(train_dataset, 
                   batch_size=batch_size, shuffle=True)
valid_loader = torch.utils.data.DataLoader(valid_dataset, 
                   batch_size=batch_size, shuffle=True)

criterion = nn.CrossEntropyLoss() # 損失の定義
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) #(確率的)勾配降下法

for epoch in range(max_epoch):
    train_epoch(model, train_loader, epoch)
    valid_epoch(model, valid_loader, epoch)

Train Epoch: 39 [117/120 (98%)]	Loss: 1.284956
Test Epoch: 9 [27/30 (90%)]	Loss: 1.007852
Train Epoch: 39 [117/120 (98%)]	Loss: 0.787336
Test Epoch: 9 [27/30 (90%)]	Loss: 0.915068
Train Epoch: 39 [117/120 (98%)]	Loss: 0.096359
Test Epoch: 9 [27/30 (90%)]	Loss: 0.302962
Train Epoch: 39 [117/120 (98%)]	Loss: 0.295645
Test Epoch: 9 [27/30 (90%)]	Loss: 0.181136
Train Epoch: 39 [117/120 (98%)]	Loss: 0.605164
Test Epoch: 9 [27/30 (90%)]	Loss: 0.241318
Train Epoch: 39 [117/120 (98%)]	Loss: 0.084802
Test Epoch: 9 [27/30 (90%)]	Loss: 0.050701
Train Epoch: 39 [117/120 (98%)]	Loss: 0.051883
Test Epoch: 9 [27/30 (90%)]	Loss: 0.024192
Train Epoch: 39 [117/120 (98%)]	Loss: 0.037929
Test Epoch: 9 [27/30 (90%)]	Loss: 0.317649
Train Epoch: 39 [117/120 (98%)]	Loss: 0.069343
Test Epoch: 9 [27/30 (90%)]	Loss: 0.136748
Train Epoch: 39 [117/120 (98%)]	Loss: 0.003237
Test Epoch: 9 [27/30 (90%)]	Loss: 0.010801


In [83]:
model._backward_hooks

OrderedDict()

## 演習:計算グラフに従って微分の計算をする
- 計算グラフは書いていながら、NNのBPは計算グラフに沿っているので、参考までに

In [55]:
x = torch.tensor([2.0 ,3.0],  requires_grad=True)
W = torch.tensor([[0., 1.], [2., 3.]], requires_grad=True)
y = torch.tensor([0., 1.], requires_grad=True)

In [56]:
loss = (y - W * x)** 2
loss = loss.sum()

In [57]:
loss.backward()

In [58]:
y.grad

tensor([ -8., -20.])

In [59]:
x.grad

tensor([16., 52.])

In [79]:
W.grad

tensor([[-0., 12.],
        [16., 48.]])

## PytorchでのOptimizer 

In [61]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.l1 = nn.Linear(3, 5)
        self.l2 = nn.Linear(5, 4)

    def forward(self, x):
        y = self.l1(x)
        y = self.l2(y)
        return y

net = Net()

## Adadelta

In [62]:
adadelta = torch.optim.Adadelta(net.parameters(), lr=1.0, rho=0.9, eps=1e-06, weight_decay=0)

In [65]:
from torch.optim.optimizer import Optimizer

In [66]:
class Adadelta(Optimizer):
    """Implements Adadelta algorithm.

    It has been proposed in `ADADELTA: An Adaptive Learning Rate Method`__.

    Arguments:
        params (iterable): iterable of parameters to optimize or dicts defining
            parameter groups
        rho (float, optional): coefficient used for computing a running average
            of squared gradients (default: 0.9)
        eps (float, optional): term added to the denominator to improve
            numerical stability (default: 1e-6)
        lr (float, optional): coefficient that scale delta before it is applied
            to the parameters (default: 1.0)
        weight_decay (float, optional): weight decay (L2 penalty) (default: 0)

    __ https://arxiv.org/abs/1212.5701
    """

    def __init__(self, params, lr=1.0, rho=0.9, eps=1e-6, weight_decay=0):
        if not 0.0 <= lr:
            raise ValueError("Invalid learning rate: {}".format(lr))
        if not 0.0 <= rho <= 1.0:
            raise ValueError("Invalid rho value: {}".format(rho))
        if not 0.0 <= eps:
            raise ValueError("Invalid epsilon value: {}".format(eps))
        if not 0.0 <= weight_decay:
            raise ValueError("Invalid weight_decay value: {}".format(weight_decay))

        defaults = dict(lr=lr, rho=rho, eps=eps, weight_decay=weight_decay)
        super(Adadelta, self).__init__(params, defaults)

    @torch.no_grad()
    def step(self, closure=None):
        """Performs a single optimization step.

        Arguments:
            closure (callable, optional): A closure that reevaluates the model
                and returns the loss.
        """
        loss = None
        if closure is not None:
            with torch.enable_grad():
                loss = closure()

        for group in self.param_groups:
            for p in group['params']:
                if p.grad is None:
                    continue
                grad = p.grad
                if grad.is_sparse:
                    raise RuntimeError('Adadelta does not support sparse gradients')
                state = self.state[p]

                # State initialization
                if len(state) == 0:
                    state['step'] = 0
                    state['square_avg'] = torch.zeros_like(p, memory_format=torch.preserve_format)
                    state['acc_delta'] = torch.zeros_like(p, memory_format=torch.preserve_format)

                square_avg, acc_delta = state['square_avg'], state['acc_delta']
                rho, eps = group['rho'], group['eps']

                state['step'] += 1

                if group['weight_decay'] != 0:
                    grad = grad.add(p, alpha=group['weight_decay'])

                square_avg.mul_(rho).addcmul_(grad, grad, value=1 - rho)
                std = square_avg.add(eps).sqrt_()
                delta = acc_delta.add(eps).sqrt_().div_(std).mul_(grad)
                p.add_(delta, alpha=-group['lr'])
                acc_delta.mul_(rho).addcmul_(delta, delta, value=1 - rho)

        return loss

In [68]:
adadelta.param_groups

[{'params': [Parameter containing:
   tensor([[-0.0827, -0.2545,  0.0653],
           [ 0.1403,  0.0586, -0.4727],
           [ 0.2888, -0.5296, -0.0437],
           [ 0.1436,  0.3394,  0.5137],
           [-0.4268, -0.0852,  0.1617]], requires_grad=True),
   Parameter containing:
   tensor([ 0.5146,  0.3544, -0.5008,  0.4203,  0.0027], requires_grad=True),
   Parameter containing:
   tensor([[-0.2886,  0.2312,  0.2758, -0.3287,  0.2043],
           [ 0.0142,  0.1444,  0.0924,  0.2030, -0.1304],
           [-0.2577, -0.1107, -0.1134,  0.2369,  0.4067],
           [ 0.3083,  0.1643,  0.2341,  0.3252,  0.1663]], requires_grad=True),
   Parameter containing:
   tensor([-0.3942, -0.1765,  0.2970,  0.2063], requires_grad=True)],
  'lr': 1.0,
  'rho': 0.9,
  'eps': 1e-06,
  'weight_decay': 0}]